server:
  port: 7777

logging:
  level:
    root: DEBUG
    org.springframework.security.web.FilterChainProxy: ERROR
    logging.level.org.hibernate.SQL: INFO
    com.zaxxer.hikari: ERROR
    org.postgresql: ERROR

spring:
  application:
    name: j-sso
  liquibase:
    enabled: true  # Указать true, если необходимо сделать накат скриптов БД при запуске приложения
    change-log: classpath:database/db.changelog.yaml
    contexts: prod, dev
  datasource:
    url: "jdbc:postgresql://localhost:5435/j-sso"
    username: "user"
    password: "user"
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-j-sso"
      register-mbeans: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
            clientId: c4c614cc6a10d5b5adf4
            clientSecret: 8b5b3dcc8337176eed4bb76dc67cd84dceaf6140

          yandex:
            provider: yandex
            clientId: 88968b5a14c6421685bb21b3fe98ea65
            clientSecret: e594434a51f042b79969dd4632b15342
            redirect-uri: http://localhost:7777/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex

        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

yandex-avatar-url: https://avatars.yandex.net/get-yapic/{avatarId}/islands-retina-50

---
spring:
  config:
    activate:
      on-profile: production
  liquibase:
    contexts: prod

---
spring:
  config:
    activate:
      on-profile: development
  liquibase:
    contexts: prod, dev